### ISSUE TITLE
In Game Video recording Urgent

### ISSUE THREAD

**Issue by suavesolutions** [EddieCameron/InputVCR#1]
Hi,

I read post and found that your software support In Game Play Recording functionality for unity Web based Games.

But the link of unity Game is not recording when i press R and than P to Play nothing happened?

We are creating a game for unity 3D web based and want to record a part of the Game and reply it and share that part on Youtube for promotion purpose.

Is your software is capable to do that?

Look forward for a quick response

Kind Regards,
Mark
Email: mark@suavesolutions.net

**Comment by AjayVenkat** [comment]
Im might be a bit late - But you misunderstand what this is for, it is to record your actions IN GAME and then replicate it again as another player.
