### ISSUE TITLE
working with Unity 5.x?

### ISSUE THREAD

**Issue by caron** [EddieCameron/InputVCR#2]
I am new to Unity and need to capture some input so I can replay those actions during a 'demo' that isn't rendered to a video but actually showing the game rendering in real-time. I think this is the right tool to use?

I tried to use the example scene in 5.3 without luck... any advice?

**Comment by caron** [comment]
wow, long time ago... is this working in 2019.2.x?

**Comment by EddieCameron** [comment]
Yes! And sorry
  

  
  

  
  
>
